### ISSUE TITLE
Create *Job Title* and *Set interview time* fields.

### ISSUE THREAD

**Issue by Jatin-tec** [himanshutrends/interview-frontend#2]
![image](https://github.com/user-attachments/assets/933e7472-3047-4380-98a6-1b7cadfe3102)
![image](https://github.com/user-attachments/assets/52541b7f-01d6-4fe3-99c9-db1bfd59347a)

**Comment by himanshutrends** [comment]
@Jatin-tec For Job Title, use same **_Input_** component as "Company Name", For date-time picker refer **/profile/reschedule/** 
```
import { DateTimePicker } from "@/components/ui/date-time-picker";
```
